version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: bvc_db
      POSTGRES_USER: bvc_user
      POSTGRES_PASSWORD: bvc_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build: ./docker/backend
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://bvc_user:bvc_password@postgres/bvc_db
      - REDIS_URL=redis://redis:6379/0

  frontend:
    build: ./docker/frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
